spring:
  profiles:
    active: prdu
  datasource:
    url: jdbc:mysql://localhost:3306/sp_boot
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true